// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_RfZgSnNULu1Yw9Xcohjh_acX9vEE6rw',
    appId: '1:307897668289:web:cd08bb23a362f5e445ba40',
    messagingSenderId: '307897668289',
    projectId: 'sidework-839c2',
    authDomain: 'sidework-839c2.firebaseapp.com',
    storageBucket: 'sidework-839c2.appspot.com',
    measurementId: 'G-N2F099PVLN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBwCWdp7uxtQ3HHOSOpzRfUO2OFc_69TPk',
    appId: '1:307897668289:ios:a70359ceaa23f83845ba40',
    messagingSenderId: '307897668289',
    projectId: 'sidework-839c2',
    storageBucket: 'sidework-839c2.appspot.com',
    iosClientId: '307897668289-1vtm6scg9pfd1t56pil4g6e73c3tfs7k.apps.googleusercontent.com',
    iosBundleId: 'com.example.sideworkWeb',
  );
}
